import React, { useEffect, useState } from 'react';
import 'tailwindcss/tailwind.css'
import Link from "next/link"
import Head from 'next/head'
function form() {

    const [list, setList] = useState([]);
    const [word, setWord] = useState('');

    const addWord = (e) =>{
        e.preventDefault();
        setList(ol => [...ol ,' '+ word]);
        document.getElementById("word").value = "";
    }

    return (
        <>
        <Head>
            <title>Formulario 🚀</title>
            <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="central">
            <div className="cabecera">
                <h1 className="tituloHola">Esta es la página de Formulario</h1>
            </div>
            <div className="botones">
                <button className="boton">
                    <Link href="/"><a className="botonPrincipal">Volver!</a></Link>
                </button>
            </div>      
        </main>
    
           <div className="caja">
               <div className="formulario">
               <form className="form" onSubmit={addWord} >
                   <label>Write a word</label>
                    <input onChange={(e)=>setWord(e.target.value)} type="text" id="word"></input>
                    <button className="botonForm">Enviar</button>
                </form>
                
                </div>
                <p className="lista">Lista:<br></br> {list}</p>
               
            </div>
        </>

    )

}

export default form;