import React, { useEffect, useState } from 'react';
import 'tailwindcss/tailwind.css'
import Link from "next/link"
import Head from 'next/head'
function form() {

    const [lista, setLista] = useState([]);
    const [palabra, setPalabra] = useState('');

    const sumar_palabra = (e) =>{
        e.preventDefault();
        setLista(ol => [...ol ,' '+ palabra]);
        document.getElementById("palabra").value = "";
    }

    return (
        <>
        <Head>
            <title>Formulario 🚀</title>
            <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="central">
            <div className="cabecera">
                <h1 className="tituloHola">Esta es la página de Formulario</h1>
            </div>
            <div className="botones">
                <button className="boton">
                    <Link href="/"><a className="botonPrincipal">Volver!</a></Link>
                </button>
            </div>      
        </main>
    
           <div className="caja">
               <div className="formulario">
               <form className="form" onSubmit={sumar_palabra} >
                   <label>Escribe una palabra</label>
                    <input onChange={(e)=>setPalabra(e.target.value)} type="text" id="palabra"></input>
                    <button className="botonForm">Enviar</button>
                </form>
                
                </div>
                <p className="lista">Lista:<br></br> {lista}</p>
               
            </div>
        </>

    )

}

export default form;