import React, { useEffect, useState } from 'react';
import 'tailwindcss/tailwind.css'
import Link from "next/link"
import Head from 'next/head'
export default function useEffectPage() {

    const [resourceType, setResourceType] = useState('agumon');
    const [items, setItems] = useState([]);
    const [todo, setTodo] = useState([]);
    const scrollToTop = () => {
        window.scrollTo({
          top: 100,
          behavior: 'smooth'
        });
      };

    // UseEffect executes function every change of array arguments:
    // useEffect(function, array_arguments (optional, can be empty array))
    // If no second argument is passed, only execute once
    // Excecutes return content when component willUnmount or 
    // before argument change.
    useEffect(() => {
        fetch(`https://digimon-api.herokuapp.com/api/digimon/name/${resourceType}`)
            .then(response => response.json())
            .then(json => setItems(json))
            scrollToTop();
            
    }, [resourceType]);
    useEffect(() => {
        fetch(`https://digimon-api.herokuapp.com/api/digimon/`)
            .then(response => response.json())
            .then(json => setTodo(json))
            
    });
    

    return (
        <>
        <Head>
            <title>Digimon 🐾</title>
            <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="central">
            <div className="cabecera">
                <h1 className="tituloHola">Esta es la página de Digimon</h1>
            </div>
            <div className="botones">
                <button className="boton">
                    <Link href="/"><a className="botonPrincipal">Volver!</a></Link>
                </button>
            </div>      
        </main>
            <h1 className="nombrePais">{resourceType}</h1>
            <ul className="cuadros">
                {items.map((item, index) => {
                    return (<ul key={index}>
                    <li  className="cuadro">
                    <br></br>Name: {JSON.stringify(item['name'])}
                    <br></br>Level: {JSON.stringify(item['level'])}
                    <br></br><img src={item['img']} className="imagenesDigimon"></img></li>
                    </ul>
                )
                })}
            </ul>
            <div className="banderas">
            {todo.map((todo, index) => {
                return (<button
                    className="bandera"
                    onClick={() => setResourceType(todo['name'])}><img 
                    src={todo['img']}></img>
                    
                </button>
                )
                })}
            </div>
        </>

    )

}